CREATE DATABASE IF NOT EXISTS Persons;
USE Persons;
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) ,
    SURNAME VARCHAR(255),
    AGE INT DEFAULT NULL ,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CONTACTS(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CUSTOMER INT,
    TYPE TINYINT(1) ,
    CONTACT VARCHAR(255),
    PRIMARy KEY(ID),
    FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
);